<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find ros_blackship)/models/define.xacro"/>
    <xacro:include filename="$(find ros_blackship)/models/config.xacro"/>
    <xacro:include filename="$(find ros_blackship)/models/property.xacro"/>

    <xacro:macro name="blackship_wheel"
                 params="parent_link suffix *origin">

        <joint name="${joint_blackship_wheel}_${suffix}" type="continuous">
            <axis xyz="0 1 0" rpy="0 0 0"/>
            <insert_block name="origin"/>
            <parent link="${parent_link}"/>
            <child link="${link_blackship_wheel}_1_${suffix}"/>
            <joint_properties damping="0.0" friction="0.0"/>
        </joint>

        <link name="${link_blackship_wheel}_1_${suffix}">
            <visual>
                <origin rpy="${DEG2RAD*90} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder radius="${blackship_wheel_radius}"
                              length="${blackship_wheel_width}"/>
                </geometry>
                <material name="wheel_belt_color">
                    <color rgba="0.1 0.1 0.1 1"/>
                </material>
            </visual>
            <collision>
                <origin rpy="${DEG2RAD*90} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder radius="${blackship_wheel_radius}"
                              length="${blackship_wheel_width}"/>
                </geometry>
            </collision>
            <inertial>
                <origin rpy="${DEG2RAD*90} 0 0" xyz="0 0 0"/>
                <mass value="${blackship_wheel_weight}"/>
                <xacro:insert_block name="blackship_wheel_inertia"/>
            </inertial>
        </link>

        <joint name="${joint_blackship_wheel}_2_${suffix}" type="fixed">
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <parent link="${link_blackship_wheel}_1_${suffix}"/>
            <child link="${link_blackship_wheel}_2_${suffix}"/>
        </joint>

        <link name="${link_blackship_wheel}_2_${suffix}">
            <visual>
                <origin rpy="${DEG2RAD*90} 0 0" xyz="0 0 0"/>
                <geometry>
                    <cylinder radius="${blackship_wheel_radius*0.8}"
                              length="${blackship_wheel_width*1.1}"/>
                </geometry>
                <material name="wheel_spoke_color">
                    <color rgba="0 0 0.8 1"/>
                </material>
            </visual>
        </link>
    </xacro:macro>


    <xacro:macro name="blackship_wheels" params="parent_center_link">
        <xacro:blackship_wheel
                parent_link="${parent_center_link}" suffix="frontleft">
            <origin rpy="0 0 0"
                    xyz="${blackship_wheel_wheelbase/2.0} ${blackship_wheel_track/2.0} 0"/>
        </xacro:blackship_wheel>

        <xacro:blackship_wheel
                parent_link="${parent_center_link}" suffix="frontright">
            <origin rpy="0 0 0"
                    xyz="${blackship_wheel_wheelbase/2.0} ${-blackship_wheel_track/2.0} 0"/>
        </xacro:blackship_wheel>

        <xacro:blackship_wheel
                parent_link="${parent_center_link}" suffix="rearleft">
            <origin rpy="0 0 0"
                    xyz="${-blackship_wheel_wheelbase/2.0} ${blackship_wheel_track/2.0} 0"/>
        </xacro:blackship_wheel>

        <xacro:blackship_wheel
                parent_link="${parent_center_link}" suffix="rearright">
            <origin rpy="0 0 0"
                    xyz="${-blackship_wheel_wheelbase/2.0} ${-blackship_wheel_track/2.0} 0"/>
        </xacro:blackship_wheel>

    </xacro:macro>

</robot>